services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: horrorbark-nginx
    depends_on:
      - php
    networks:
      - internal
    ports:
      - "8081:80"
    volumes:
      - ./application/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: horrorbark-php
    expose:
      - "9000"
    networks:
      - internal
    volumes:
      - ./application/:/var/www/html/

  mysql:
    image: mysql:8.0
    container_name: db
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "horrorbark"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_password"
    networks:
      - internal
    volumes:
      - db-data:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  db-data:
